name: Steps if conditional bugs

on: push

jobs:
  build:
    name: Fail
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    steps:
      - name: Deploy
        run: exit 1
  notify:
    name: Notify-1
    runs-on: 'ubuntu-latest'
    needs: build
    if: always()
    steps:
      - name: Slack Notification
        run: echo "Failure"
        if: needs.build.result == 'failure'
  notify2:
    name: Notify-2
    runs-on: 'ubuntu-latest'
    needs: build
    if: always()
    steps:
      - name: Slack Notification
        run: echo "Failure"
        if: needs.build.result == 'success'
  notify3:
    name: Notify-3
    runs-on: 'ubuntu-latest'
    needs: build
    if: needs.build.result == 'failure'
    steps:
      - name: Slack Notification
        run: echo "Failure"
  notify4:
    name: Notify-4
    runs-on: 'ubuntu-latest'
    needs: build
    if: needs.build.result == 'failure' && always()
    steps:
      - name: Slack Notification
        run: echo "Failure"
