name: Steps if conditional bugs
on: [push, pull_request]
jobs:
  bug:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-lastest, ubuntu-18.04]
        node: [6, 8, 10]
    steps:

      - name: Upload artifacts (with if true check)
        if: ${{ 0 == 0 }}
        run: echo "zero equals zero ${{ 0 == 0 }}"
