name: Steps if conditional bugs

on: push

jobs:
  job_a:
    name: Always fail
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
  job_b:
    name: Notify
    runs-on: ubuntu-latest
    needs: job_a
    if: 0 == 0 
    steps:
      - name: Notify
        run: echo "Job A failed!" and ${{needs.job_a.result}} and ${needs.job_a.result}
