
name: CI CD

on:
  pull_request:

jobs:
  build:
    name: Build something
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 Done"

  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      - i-do-not-exist
    steps:
      - name: Step 1
        run: echo "Step 1 Done"
